twig:
    default_path: '%kernel.project_dir%/templates'
    # Frontend layout
    form_themes: ['bootstrap_5_layout.html.twig']
    # Translations
    globals: 
        locales: '%app.locales%'
    
when@test:
    twig:
        strict_variables: true
