twig:
    default_path: '%kernel.project_dir%/templates'
    # choix du framework pour le frontend
    form_themes: ['bootstrap_5_layout.html.twig']
    
when@test:
    twig:
        strict_variables: true
